# Generated by Django 5.2 on 2025-04-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpaaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.TextField()),
                ('duration', models.IntegerField()),
                ('genre', models.JSONField()),
                ('language', models.CharField(max_length=50)),
                ('user_rating', models.IntegerField()),
                ('mpaa_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.mpaarating')),
            ],
        ),
    ]
